name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 #v1.16.1
        with:
          components: clippy, rustfmt

      - name: Format
        run: cargo fmt --all --check

      - name: Check
        run: cargo check --all-targets && cargo check --all-targets --features pkce-auth

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings && cargo clippy --all-targets --features pkce-auth -- -D warnings

      - name: Test
        run: cargo test --all-targets && cargo test --all-targets --features pkce-auth

      - name: Docs
        run: RUSTDOCFLAGS='-D warnings' cargo doc --no-deps

      - name: Doc Tests
        run: cargo test --doc

      - name: Publish dry run
        run: cargo publish --dry-run
